name: CI/CD, Infrastructure & Automation
quadrant: 3
entries:
  - label: Docker
    link: https://www.docker.com/
    ring: adopt
    active: true
    moved: 0
  - label: GitLab CI
    link: https://docs.gitlab.com/ee/ci/
    ring: adopt
    active: true
    moved: 0
  - label: GitHub Actions
    link: https://github.com/features/actions
    ring: adopt
    active: true
    moved: 0
  - label: Kibana
    link: https://www.elastic.co/kibana/
    ring: adopt
    active: true
    moved: 0
  - label: Terraform
    link: https://www.terraform.io/
    ring: trial
    active: true
    moved: 0
  - label: SonarQube
    link: https://www.sonarqube.org/
    ring: assess
    active: true
    moved: 0
  - label: Chromatic
    link: https://www.chromatic.com/
    ring: assess
    active: true
    moved: 0
